# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd
import pymongo
from bson.decimal128 import Decimal128

### Code to upload data through terminal:

mongoimport --db uk_food --collection establishments --file establishments.json --jsonArray

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
mongo.list_database_names()

['admin', 'config', 'local', 'uk_food']

In [4]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [5]:
# review the collections in our database
db.list_collection_names()

['establishments']

In [6]:
# assign the collection to a variable
establishments = db['establishments']

In [7]:
for doc in establishments.find().limit(5):
    pprint(doc['scores'])

{'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}
{'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}
{'ConfidenceInManagement': 10, 'Hygiene': 5, 'Structural': 5}
{'ConfidenceInManagement': 10, 'Hygiene': 0, 'Structural': 0}
{'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 5}

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [8]:
# Find the establishments with a hygiene score of 20
establishments_with_score_20 = establishments.find({'scores.Hygiene': 20})

# Convert the result to a Pandas DataFrame now instead of later so we avoid using next on cursor object
df = pd.DataFrame(list(establishments_with_score_20))
df


# Use count_documents to display the number of documents in the result
result = establishments.count_documents({'scores.Hygiene': 20})
print("Number of establishments with a hygiene score of 20: ", result)

# Display the first document in the results using pprint
first_establishment = df.iloc[0]  # gets the first row of the DataFrame
pprint(first_establishment)

Number of establishments with a hygiene score of 20:  41
_id                                                    6462e639ba9bfd9024b1bb35
FHRSID                                                                   110681
ChangesByServerID                                                             0
LocalAuthorityBusinessID                                                   4029
BusinessName                                                The Chase Rest Home
BusinessType                                                    Caring Premises
BusinessTypeID                                                                5
AddressLine1                                               5-6 Southfields Road
AddressLine2                                                         Eastbourne
AddressLine3                                                        East Sussex
AddressLine4
PostCode                                                               BN21 1BU
Phone
RatingValue                                                                   5
RatingKey                                                          fhrs_0_en-gb
RatingDate                                                  2021-09-23T00:00:00
LocalAuthorityCode                                                          102
LocalAuthorityName                                                   Eastbourne
LocalAuthorityWebSite                  http://www.eastbourne.gov.uk/foodratings
LocalAuthorityEmailAddress                      Customerfirst@eastbourne.gov.uk
scores                        {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...
SchemeType                                                                 FHRS
geocode                        {'longitude': 0.08384000, 'latitude': 50.769705}
RightToReply
Distance                                                            4613.888288
NewRatingPending                                                          False
meta                          {'dataSource': None, 'extractDate': '0001-01-0...
links                         [{'rel': 'self', 'href': 'https://api.ratings....
Name: 0, dtype: object

In [9]:

# Display the number of rows in the DataFrame
dfrows=len(df)
print(dfrows) #equal to the number of establishments with hygeine score of 20


# Display the first 10 rows of the DataFrame
df.head(10)

41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,6462e639ba9bfd9024b1bb35,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,6462e639ba9bfd9024b1bec3,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,6462e63aba9bfd9024b1c1c9,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,6462e63aba9bfd9024b1c3b4,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,6462e63aba9bfd9024b1c3bd,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,6462e63aba9bfd9024b1cd5e,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,6462e63aba9bfd9024b1cf7a,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,6462e63aba9bfd9024b1e4a8,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,6462e63aba9bfd9024b1e8ee,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.18594...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,6462e63aba9bfd9024b1f0fc,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [10]:
unique_authorities = establishments.distinct('LocalAuthorityName')
if 'London' in unique_authorities:
    print('London is in the list')
else:
    print('London is not in the list')

London is not in the list

In [11]:
unique_authorities = establishments.distinct('AddressLine3')
if 'London' in unique_authorities:
    print('London is in the list')
else:
    print('London is not in the list')

London is in the list

### London exists in AddressLine3 but not in Locl Authority Name

In [69]:
test = establishments.find({'LocalAuthorityName': 'London'})
list(test)

[]

## London not in the Local Establishment Name????

In [67]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
establishments_london = establishments.find({'$and': [{'LocalAuthorityName': 'London'}, {'RatingValue': {'$gte': 4}}]})

# Convert the result to a Pandas DataFrame
df_london = pd.DataFrame(list(establishments_london))

# Use count_documents to display the number of documents in the result
result = establishments.count_documents({'$and': [{'LocalAuthorityName': 'London'}, {'RatingValue': {'$gte': 4}}]})

# Display the first document in the results using pprint
first_establishment = df_london.iloc[0]

IndexError: single positional indexer is out-of-bounds

### I get an error above because London is not in the LocalAuthorityName List so providing the code that would work if it was

### You can double chekc the JSON file as well. There is no London in LocalAuthorityName

In [51]:
# Display the number of rows in the DataFrame
print(len(df_london))
# Display the first 10 rows of the DataFrame
df_london.head(10)

0

Empty DataFrame
Columns: []
Index: []

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [96]:
from decimal import Decimal

In [103]:
latitude

Decimal128('51.49014200')

In [104]:
longitude

Decimal128('0.08384000')

In [105]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
penang_flavours = establishments.find_one({"BusinessName": "Penang Flavours"})
latitude = penang_flavours['geocode']['latitude']
latitude=51.49014200
longitude = penang_flavours['geocode']['longitude']
longitude=0.08384000 #Just copy pasting and hardcoding because this is annoying


query = establishments.find({
    '$and': [
        {'geocode.latitude': {'$gte': latitude - degree_search}},
        {'geocode.latitude': {'$lte': latitude + degree_search}},
        {'geocode.longitude': {'$gte': longitude - degree_search}},
        {'geocode.longitude': {'$lte': longitude + degree_search}},
        {'RatingValue': 5}
    ]
}).sort('scores.Hygiene', pymongo.ASCENDING).limit(5) #Ascending because a low hygeine score is better according to the bootcamp spot information, so if we want the lowest
                                                        #hygeine score first we want the highest number first

results = list(query)

In [108]:
# Convert result to Pandas DataFrame
df_penang_flavours = pd.DataFrame(results)
df_penang_flavours

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,6462e63aba9bfd9024b1ed4a,1354861,0,21/00075/CP,King Kebab,Takeaway/sandwich shop,7844,George And Dragon,East Tilbury Road,Linford,...,http://www.thurrock.gov.uk/food,foodsafety@thurrock.gov.uk,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.487892}",,4635.358978,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
1,6462e63aba9bfd9024b1f1aa,1523742,0,22/00141/CP,Martins,Retailers - other,4613,Defoe Parade Post Office,3 Defoe Parade,Chadwell St Mary,...,http://www.thurrock.gov.uk/food,foodsafety@thurrock.gov.uk,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.4880323}",,4636.798351,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
2,6462e63aba9bfd9024b1f169,1525936,0,22/00151/CP,The Muscle Market,Retailers - other,4613,The Cutting Edge Hair Studio,7A Brentwood Road,Chadwell St Mary,...,http://www.thurrock.gov.uk/food,foodsafety@thurrock.gov.uk,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.4822432}",,4636.702362,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
3,6462e63aba9bfd9024b1eb45,390283,0,05/00101/CP,East Tilbury Post Office,Retailers - other,4613,East Tilbury Post Office & Convenie,2 - 3 Stanford House,Princess Margaret Road,...,http://www.thurrock.gov.uk/food,foodsafety@thurrock.gov.uk,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.48062...",,4634.857917,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
4,6462e63aba9bfd9024b1eb42,390400,0,09/00040/CP,Nancy's Sandwich Bar,Restaurant/Cafe/Canteen,1,7 Stanford House,Princess Margaret Road,East Tilbury,...,http://www.thurrock.gov.uk/food,foodsafety@thurrock.gov.uk,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': 0.08384000, 'latitude': 51.480638}",,4634.858687,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [112]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

pipeline = [
    {'$match': {'scores.Hygiene': 0}},
    {'$group': {'_id': '$LocalAuthorityName','count': {'$sum': 1 }}},
    {'$sort': {'count': -1}}]

results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result

# Print the first 10 results
print("Number of documents in the result: ", len(results))
print("First 10 results: ", results[:10])

Number of documents in the result:  55
First 10 results:  [{'_id': 'Thanet', 'count': 1130}, {'_id': 'Greenwich', 'count': 882}, {'_id': 'Maidstone', 'count': 713}, {'_id': 'Newham', 'count': 711}, {'_id': 'Swale', 'count': 686}, {'_id': 'Chelmsford', 'count': 680}, {'_id': 'Medway', 'count': 672}, {'_id': 'Bexley', 'count': 607}, {'_id': 'Southend-On-Sea', 'count': 586}, {'_id': 'Tendring', 'count': 542}]

In [113]:
# Convert the result to a Pandas DataFrame
df_hygiene_0 = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print(len(df_hygiene_0))

# Display the first 10 rows of the DataFrame
df_hygiene_0.head(10)

55

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542